FROM docker pull maven:3.9.6 AS build
COPY..
RUN mvn clean package -DskipTests

FROM openjdk:22-jdk-slim
COPY --from=build/target/explore-0.0.1-SNAPSHOT.jar explore.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","demo.jar"]